djangostudy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feeds import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.SignUpView.as_view(), name='sign_up'),
]

feeds/urls.py
from django.urls import path
from feeds import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.FeedListView.as_view(), name='index'),

    # path('new/', views.new, name='new'),
    path('new/', views.FeedCreateView.as_view(), name='new'),

    # path('<int:id>/', views.show, name='show'),
    path('<int:pk>/', views.FeedDetailView.as_view(), name='show'),

    # path('<int:id>/edit', views.edit, name='edit'),
    path('<int:pk>/edit', views.FeedUpdateView.as_view(), name='edit'),

    # path('<int:id>/delete', views.delete, name='delete'),
    path('<int:pk>/delete', views.FeedDeleteView.as_view(), name='delete'),

    path('<int:id>/comments/', views.create_comment, name='create_comment'),
    path('<int:id>/comments/<int:cid>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.feed_like, name='like'),
]

feeds/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Feed(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set', through='Like')     # 추가

    def update_date(self):
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('show', kwargs={'pk': self.pk}) # 여기로 리다이렉트해라..>?
        # CreateView, UpdateView의 default success_url
        # url의 이름을 view에서 어떻게 사용하느냐
        # **? kwargs란: 딕셔너리 형태로 되어 있어서 두 번 풀어 줘야 함

class FeedComment(models.Model):
    content = models.TextField()
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

feeds/views.py
from django.shortcuts import render
from .models import Feed, FeedComment, Like, Follow
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponse
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from django.middleware import csrf



class FeedListView(ListView):
    #model = Feed #어떤 모델이 적용될지
    queryset = Feed.objects.order_by('-created_at')
    template_name = 'feeds/index.html' # default: feeds/feed_list.html
    context_object_name = 'feeds' #default: object_list, 모델을 다루는 경우는 추가로 feed_list

class FeedDetailView(DetailView):
    model = Feed
    template_name = 'feeds/show.html'
    context_variable_name = 'feed'

class FeedCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    model = Feed
    fields = ['title', 'content']
    template_name = 'feeds/new.html'  # defalut: 'feeds/feed_create_form.html'.
 
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class FeedUpdateView(UpdateView):
    model = Feed
    fields = ['title', 'content']
    template_name = 'feeds/edit.html'  # defalut: 'feeds/feed_update_form.html'.
    context_variable_name = 'feed'

class FeedDeleteView(DeleteView):
    model = Feed
    success_url = reverse_lazy('index')
    # template_name의 default값은 'feeds/feed_confirm_delete.html'

def feed_like(request, pk):
    feed = Feed.objects.get(id = pk)
    likeList = feed.like_set.filter(user_id = request.user.id)
    if likeList.count() > 0:
        feed.like_set.get(user_id = request.user.id).delete()
    else:
        Like.objects.create(user_id = request.user.id, feed_id = pk)
    return redirect ('/feeds')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def index(request):
    if request.method == 'GET':
        feeds = Feed.objects.all()
        return render(request, 'feeds/index.html', {'feeds': feeds})
    elif request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        Feed.objects.create(title=title, content=content)
        return redirect('/feeds')

def new(request):
    return render(request, 'feeds/new.html', {})

def show(request, id):
    if request.method == 'GET': # show
        feed = Feed.objects.get(id=id)
        return render(request, 'feeds/show.html', {'feed': feed})
    elif request.method == 'POST': # update
        title = request.POST['title']
        content = request.POST['content']
        feed = Feed.objects.get(id=id)
        feed.title = title
        feed.content = content
        feed.save()
        feed.update_date()
        return redirect('/feeds/' + str(id))

def edit(request, id):
    feed = Feed.objects.get(id=id)
    return render(request, 'feeds/edit.html', {'feed': feed})

def delete(request, id):
    feed = Feed.objects.get(id=id)
    feed.delete()
    return redirect('/feeds')

def create_comment(request, id):
    if request.method == 'POST':
        content = request.POST.get('content')
        author = User.objects.get(id=request.user.id)
        response_data = {}

        token = request.META.get('CSRF_COOKIE', None)
        if token is None:
            token = csrf._get_new_csrf_key()
            request.META['CSRF_COOKIE'] = token
        request.META['CSRF_COOKIE_USED'] = True

        comment = FeedComment.objects.create(feed_id=id, content=content, author=author)
        response_data['content'] = comment.content
        response_data['comment_id'] = comment.id
        response_data['feed_id'] = comment.feed_id
        response_data['comment_author'] = comment.author.username
        response_data['token'] = token

    return JsonResponse(response_data)

def delete_comment(request, id, cid):
    c = FeedComment.objects.get(id=cid)
    c.delete()
    return redirect('/feeds')

def Lets_Follow(request, pk): #추가
    follow_from = request.user
    follow_to = User.objects.get(id = pk)

    try:
        following_already = Follow.objects.get(follow_from=follow_from, follow_to=follow_to)
    except Follow.DoesNotExist:
        following_already = None

    if following_already:
        following_already.delete()
    else:
        # Follow.objects.create(follow_from=follow_from, follow_to=follow_to)
        f = Follow()
        f.follow_from, f.follow_to = follow_from, follow_to
        f.save()

    return redirect('/feeds')

feeds/templates/feeds/edit.html
{% extends "base.html" %}

{% block content %}
  <form action="{% url 'edit' feed.id %}" method='POST'>
    {% csrf_token %}
    <p>title</p>
    <input name="title" value="{{ feed.title }}" /> <br />
    <p>content</p>
    <input name="content" value="{{ feed.content }}" /> <br />
    <input type="submit" value="submit" />
  </form>
{% endblock content %}

<!-- 
generic view 사용 안 한 경우에서는
<form action="/feeds/{{ feed.id }}/" method="POST">
이렇게 쓴다
-->

feeds/templates/feeds/index.html
{% extends "base.html" %}

{% block content %}


<h1>feed page</h1>

<form action="/feeds/new">
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" >
    new feed
  </button>
</form>

<div class="content-grid mdl-grid">
{% for feed in feeds %}

<div class="mdl-cell mdl-cell--4-col mdl-cell--stretch">
    
<!-- Wide card with share menu button -->
<style>
    .demo-card-wide.mdl-card {
      width: 100%;
    }
    .demo-card-wide > .mdl-card__title {
      color: rgba(0, 0, 0, 0.863);
      
    }
    .demo-card-wide > .mdl-card__menu {
      color: rgb(70, 196, 164);
    }
    .mdl-card__supporting-text{
      background-color: blue;
      color: antiquewhite;
    }
    </style>


    <div class="demo-card-wide mdl-card mdl-shadow--2dp">
      <br>
      <div style="text-align: left;">
      <div class="mdl-card__title-text">
            {{ feed.title }}
      </div>
    </div>  
      <div class="mdl-card__title">
      <h3>{{ feed.content }}</h3>
    </div>
      <div class="mdl-card__supporting-text">
        <h4><strong>{{feed.author.username}}</strong></h4>
      
        {% if request.user != feed.author %}
        <form action="/feeds/feeds/{{ feed.author.id }}/follow">
          {% if request.user not in feed.author.follows.all %}
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">favorite_border</i>
          </button>
          {% else %}
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">favorite</i>
          </button>
          {% endif %}
        </form>
        {% endif %}
        <span class="mdl-badge" data-badge={{ feed.author.follow_from.all.count }}>following</span>
        <span class="mdl-badge" data-badge={{ feed.author.follow_to.all.count }}>follower</span>
      </div>

      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="comment-list{{ feed.id }}">
            {% for c in feed.feedcomment_set.all %}
                <p>{{c.author.username}}: {{c.content}}</p>
                <form action="/feeds/{{ feed.id }}/comments/{{ c.id }}/" method="POST">
                    {% csrf_token %}
                    <button>댓글 삭제</button>
                </form>
            {% endfor %}    
        </div>
        <form action="/feeds/{{ feed.id }}/comments/" method="POST">
          {% csrf_token %}
          <input id="comment-content{{ feed.id }}" type="text" name="content" />
          <button id="comment-submit{{ feed.id }}" class="comment-button-all" data-number="{{ feed.id }}">댓글 달기</button>
        </form>
      
      </div>
      
        
        <div class="mdl-card__menu">
        

            <a href="/feeds/{{ feed.id }}/like"> <span class="mdl-badge"
              data-badge={{ feed.like_user_set.count }}>Likes</span></a>
        
        
        </div>
        <p></p>
        <div style="text-align: right;">
          
          <a href="/feeds/{{ feed.id }}">더보기</a>
          <form action="/feeds/{{ feed.id }}/delete" method='POST'>
            {% csrf_token %}
            <button type="submit">삭제</button>
          </form>
        </div>

    </div>
  </div>
{% endfor %}
</div>

{% endblock content %}

feeds/templates/feeds/new.html
{% extends "base.html" %}

{% block content %}
    <h1>new feed</h1>
    <form action="{% url 'new' %}" method="POST">  
        {% csrf_token %}
        <p>title</p>
        <input name="title" /> <br />
        <p>content</p>
        <input name="content" /> <br />
        <input type="submit" value="submit" />
    </form>
{% endblock content %}

feeds/templates/feeds/show.html
<div>
  <a href="/feeds">home</a>
  <a href="/feeds/{{ feed.id }}/edit">edit</a>
  <p>{{ feed.title }}</p>
  <p>작성자: {{feed.author.username}}</p>
  <p>{{ feed.content }}</p>
</div>