djangostudy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feeds import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.SignUpView.as_view(), name='sign_up'),
]

events/urls.py
from django.urls import path
from events import views

urlpatterns = [
    path('', views.EventListView.as_view(), name='index'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='show'), # pk = primary key
    path('new/', views.EventCreateView.as_view(), name='new'),
    path('<int:pk>/edit', views.EventUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.EventDeleteView.as_view(), name='delete'),
    path('<int:id>/comments/', views.create_comment, name='create_comment'),
    path('<int:id>/comments/<int:cid>/', views.delete_comment, name='delete_comment'),
]

feeds/urls.py
from django.urls import path
from feeds import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.FeedListView.as_view(), name='index'),

    # path('new/', views.new, name='new'),
    path('new/', views.FeedCreateView.as_view(), name='new'),

    # path('<int:id>/', views.show, name='show'),
    path('<int:pk>/', views.FeedDetailView.as_view(), name='show'),

    # path('<int:id>/edit', views.edit, name='edit'),
    path('<int:pk>/edit', views.FeedUpdateView.as_view(), name='edit'),

    # path('<int:id>/delete', views.delete, name='delete'),
    path('<int:pk>/delete', views.FeedDeleteView.as_view(), name='delete'),

    path('<int:id>/comments/', views.create_comment, name='create_comment'),
    path('<int:id>/comments/<int:cid>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.feed_like, name='like'),
]

events/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=256)
    date = models.DateField(auto_now_add=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)

    def update_date(self):
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('show', kwargs={'pk': self.pk})

class EventComment(models.Model):
    content = models.TextField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id)

events/views.py
from django.shortcuts import render
from .models import Event, EventComment
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
class EventListView(ListView):
    model = Event  # 어떤 모델이 적용될 것인지
    template_name = 'events/index.html'  # default: events/event_list.html
    context_object_name = 'events'  # default: object_list, 모델을 다루는 경우 추가로 feed_list

class EventDetailView(DetailView):
    model = Event
    template_name = 'events/show.html'  # default: events/detail.html
    context_variable_name = 'event'

class EventCreateView(CreateView):
    model = Event
    fields = ['title', 'date']
    template_name = 'events/new.html'

class EventUpdateView(UpdateView):
    model = Event
    fields = ['title', 'date']
    template_name = 'events/edit.html'
    context_variable_name = 'event'

class EventDeleteView(DeleteView):
    model = Event
    success_url = reverse_lazy('index')

def create_comment(request, id):
    content = request.POST['content']
    EventComment.objects.create(event_id=id, content=content)
    return redirect('/events')

def delete_comment(request, id, cid):
    c = EventComment.objects.get(id=cid)
    c.delete()
    return redirect('/events')

events/templates/events/edit.html
<form action="" method="POST">
    {% csrf_token %}
    <p>title</p>
    <input name="title" value="{{ event.title }}" /> <br />
    <p>date</p>
    <input name="date" value="{{ event.date }}" /> <br />
    <input type="submit" value="submit" />
  </form>

events/templates/events/index.html
<h1>event page</h1>
<a href="/events/new">new event</a>
{% for event in events %}
  <div style="border: 1px solid grey;">
    <a href="/events/{{ event.id }}">더보기</a>
    <form action="/events/{{ event.id }}/delete" method='POST'>
      {% csrf_token %}
      <button type="submit">삭제</button>
    </form>
    <p>{{ event.title }}</p>
    <p>{{ event.date }}</p>
    {% for c in event.eventcomment_set.all %}
      <p>ㄴ {{ c.content }}</p>
      <form action="/events/{{ event.id }}/comments/{{ c.id }}/" method="POST">
        {% csrf_token %}
        <button>댓글 삭제</button>
      </form>
    {% endfor %}
    <form action="/events/{{ event.id }}/comments/" method="POST">
      {% csrf_token %}
      <input type="text" name="content" />
      <button type="submit">댓글 달기</button>
    </form>
  </div>
{% endfor %}

events/templates/events/new.html
<h1>new event</h1>
<form action="" method="POST">
  {% csrf_token %}
  <p>title</p>
  <input name="title" /> <br />
  <p>date</p>
  <input name="date" /> <br />
  <input type="submit" value="submit" />
</form>

events/templates/events/show.html
<div>
    <a href="/events">home</a>
    <a href="/events/{{ event.id }}/edit">edit</a>
    <p>{{ event.title }}</p>
    <p>{{ event.date }}</p>
</div>