djangostudy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feeds import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.SignUpView.as_view(), name='sign_up'),
]

feeds/urls.py
from django.urls import path
from feeds import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.FeedListView.as_view(), name='index'),

    # path('new/', views.new, name='new'),
    path('new/', views.FeedCreateView.as_view(), name='new'),

    # path('<int:id>/', views.show, name='show'),
    path('<int:pk>/', views.FeedDetailView.as_view(), name='show'),

    # path('<int:id>/edit', views.edit, name='edit'),
    path('<int:pk>/edit', views.FeedUpdateView.as_view(), name='edit'),

    # path('<int:id>/delete', views.delete, name='delete'),
    path('<int:pk>/delete', views.FeedDeleteView.as_view(), name='delete'),

    path('<int:id>/comments/', views.create_comment, name='create_comment'),
    path('<int:id>/comments/<int:cid>/', views.delete_comment, name='delete_comment'),
    path('<int:pk>/like/', views.feed_like, name='like'),
]

homes/urls.py
# ./homes/urls.py
from django.conf.urls import include
from django.urls import path
from homes import views

app_name = 'homes' # 추가
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.show, name='show'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/reviews/', views.create_review, name='create_review'),
    path('<int:id>/reviews/<int:review_id>/', views.delete_review, name='delete_review'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.SignUpView.as_view(), name='sign_up'),
]

homes/models.py
# ./homes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from faker import Faker
import datetime
import random


# Create your models here.
class Home(models.Model):
    title = models.CharField(max_length=256)
    host = models.ForeignKey(User, on_delete=models.CASCADE)  # 추가
    address = models.TextField()
    # 예약 날짜는 특정하지 않고 숙소만 등록하고 싶은 경우를 위해 available_dates에 null=True 추가
    available_dates_start = models.DateField(default=datetime.date.today, null=True)
    available_dates_end = models.DateField(default=datetime.date.today() + datetime.timedelta(days=30), null=True) # 오늘로부터 30일 후
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)

    def update_date(self):
        self.updated_at = timezone.now()
        self.save()

    def seed(count):
        myfake = Faker('ko_KR')
        host_id = random.randint(1, User.objects.all().count())
        for i in range(count):
            Home.objects.create(
                title=myfake.bs(),
                host_id=host_id,
                address=myfake.address(),
                available_dates_start=myfake.date(),
                available_dates_end=myfake.date()
            )

    def __str__(self):
        return self.title


class Review(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 추가
    home = models.ForeignKey(Home, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)


    def seed(count):
        myfake = Faker('ko_KR')
        for i in range(count):
            author_id = random.randint(1, User.objects.all().count())
            home_id = random.randint(1, Home.objects.all().count())
            Review.objects.create(
                content=myfake.catch_phrase(),
                home=Home.objects.get(id=home_id),
                author_id=author_id
            )

    def __str__(self):
        return str(self.id)

homes/views.py
# ./homes/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from .models import Home, Review
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


def index(request):
    if request.method == 'GET': # index
        homes = Home.objects.all()
        return render(request, 'homes/index.html', {'homes': homes})
    elif request.method == 'POST': # create
        title = request.POST['title']
        address = request.POST['address']
        available_dates_start = request.POST['available_dates_start']
        available_dates_end = request.POST['available_dates_end']
        if available_dates_start == "": # ""는 date가 아니므로
            available_dates_start = None
        if available_dates_end == "":
            available_dates_end = None
        Home.objects.create(
            title=title,
            address=address,
            available_dates_start=available_dates_start,
            available_dates_end=available_dates_end
        )
        return redirect('/homes')


def new(request):
    return render(request, 'homes/new.html', {})


def show(request, id):
    if request.method == 'GET': # show
        home = get_object_or_404(Home, pk=id) # 해당 id의 object가 없을 경우 404 에러를 띄워 줌. 편리!
        return render(request, 'homes/show.html', {'home': home})
    elif request.method == 'POST': # update
        title = request.POST['title']
        address = request.POST['address']
        available_dates_start = request.POST['available_dates_start']
        available_dates_end = request.POST['available_dates_end']
        if available_dates_start == "":
            available_dates_start = None
        if available_dates_end == "":
            available_dates_end = None
        home = Home.objects.get(id=id)
        home.title = title
        home.address = address
        home.available_dates_start = available_dates_start
        home.available_dates_end = available_dates_end
        home.save()
        home.update_date()
        return redirect('/homes/' + str(id))


def edit(request, id):
    home = Home.objects.get(id=id)
    return render(request, 'homes/edit.html', {'home': home})


def delete(request, id):
    home = Home.objects.get(id=id)
    home.delete()
    return redirect('/homes')


def create_review(request, id):
    content = request.POST['content']
    author_id = request.user.id
    Review.objects.create(home_id=id, content=content, author_id=author_id)
    return redirect('/homes')


def delete_review(request, id, review_id):
    c = Review.objects.get(id=review_id)
    c.delete()
    return redirect('/homes')


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

homes/templates/homes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}

    {% block content %}
    <form action="/homes/{{ home.id }}/" method="POST">
        {% csrf_token %}
        <p>제목</p>
        <input name="title" value="{{ home.title }}"/>
        <p>주소</p>
        <input name="address" value="{{ home.address }}"/>
        <p>예약 가능 날짜</p>
        <!-- 날짜 field의 경우 value를 넣어도 표시되지 않기 때문에 굳이 value를 지정하지 않겠습니다. -->
        <input type="date" name="available_dates_start"/> ~ <input type="date" name="available_dates_end"/><br><br>
        <input type="submit" value="submit"/>
    </form>
    {% endblock content %}
</body>
</html>

homes/templates/homes/index.html
<!-- ./homes/templates/homes/index.html -->

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AirLion</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}
    <h1>모든 숙소 보기</h1>
    <a href="/homes/new">숙소 추가</a><br><br>
    {% for home in homes %}
        <div style="border: 1px solid grey;">
            <a href="{% url 'homes:show' home.id %}">더보기</a>
            <form action="{% url 'homes:delete' home.id %}" method='POST'>
                {% csrf_token %}
                <button type="submit">삭제</button>
            </form>
            <p>제목: {{ home.title }}</p>
            <p>주소: {{ home.address }}</p>
            <p>예약 가능 날짜: {{ home.available_dates_start }} ~ {{ home.available_dates_end }}</p>
            {% for review in home.review_set.all %}
              <p>ㄴ {{ review.content }}</p>
              <form action="/homes/{{ home.id }}/reviews/{{ review.id }}/" method="POST">
                {% csrf_token %}
                <button>리뷰 삭제</button>
              </form>
            {% endfor %}
            <form action="/homes/{{ home.id }}/reviews/" method="POST">
              {% csrf_token %}
              <input type="text" name="content" />
              <button type="submit">리뷰 저장</button>
            </form>
        </div><br>
    {% endfor %}
{% endblock content %}

</body>
</html>

homes/templates/homes/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}

    {% block content %}
    <!-- ./homes/templates/homes/new.html -->
    <h1>숙소 등록</h1>
    <form action="/homes/" method="POST">
        {% csrf_token %}
        <p>제목</p>
        <input name="title"/>
        <p>주소</p>
        <input name="address"/>
        <p>예약 가능 날짜</p>
        <input type="date" name="available_dates_start"/> ~ <input type="date" name="available_dates_end"/>
        <input type="submit" value="submit"/>
    </form>
    {% endblock content %}
</body>
</html>

homes/templates/homes/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}

    {% block content %}
    <div>
      <a href="/homes">home</a>
      <a href="/homes/{{ home.id }}/edit">edit</a>
      <p>제목: {{ home.title }}</p>
      <p>주소: {{ home.address }}</p>
      <p>예약 가능 날짜: {{ home.available_dates_start }} ~ {{ home.available_dates_end }}</p>
    </div>
    {% endblock content %}
</body>
</html>